
CREATE OR REPLACE TASK RAW.CRM.TASK_LOAD_INFINITY_DOWNLOAD
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 30 6 * * * Europe/London'
AS
  CALL RAW.CRM.sp_load_infinity_download();

 ALTER TASK RAW.CRM.TASK_LOAD_INFINITY_DOWNLOAD RESUME; 