use role  accountadmin;

CREATE OR REPLACE TABLE reporting.details.BIGMW1_DAILY_REPORT_BREAKDOWN (
    DATE VARCHAR,
    PARTNER VARCHAR,
    SUB_ACCOUNT VARCHAR,
    SCHEME VARCHAR,
    JOB_NUMBER VARCHAR,
    VRN VARCHAR,
    VEHICLE_MAKE VARCHAR,
    VEHICLE_MODEL VARCHAR,
    REPORTED_SYMPTOM VARCHAR,
    FAULT_DESCRIPTION VARCHAR,
    FAULT_CAUSE VARCHAR,
    FAULT_ACTION VARCHAR,
    RESOURCE_TYPE VARCHAR,
    JOB_TYPE_NAME VARCHAR,
    TOW_DESTINATION VARCHAR,
    TOW_DISTANCE VARCHAR,
    SERVICE_BREAKDOWN_COUNT VARCHAR
);
