CREATE TABLE reporting.details.bmw_commission_site_comm (
    TRANSACTION_CREATION_DATE_TIME VARCHAR,
    AGREEMENT_NUMBER VARCHAR,
    TRANS_TYPE_CODE VARCHAR,
    TRANS_TYPE_DESC VARCHAR,
    THIRD_PARTY_ID_CODE VARCHAR,
    TRADING_NAME VARCHAR,
    DEBIT_VALUE VARCHAR,
    CREDIT_VALUE VARCHAR,
    ADVANCE VARCHAR,
    CUSTOMER_NAME VARCHAR,
    REGISTRATION_PLATE VARCHAR,
    COMPONENT_LIVE_DATE VARCHAR,
    PRODUCT VARCHAR,
    CREDIT_PERCENT VARCHAR
);
