use role accountadmin;

CREATE TABLE reporting.details.BMW_COMMISSION_RECONCILIATION (
    CODE VARCHAR,
    SITE_NAME VARCHAR,
    DEBIT VARCHAR,
    CREDIT VARCHAR,
    STATEMENT_TOTAL VARCHAR,
    ACTION_REQUIRED VARCHAR
);